name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs && npm install

    - name: Format and lint PHP code
      run: composer run lint:php

    - name: Format and lint JS code
      run: composer run format:js && composer run lint:js
    
    # TODO: Fix CSS errors
    #- name: Format and lint CSS code
    #  run: composer run lint:css
    
    # TODO: Add tests
    # - name: Run test suite
    #   run: composer run-script test
